---
- name: nginx is installed
  become: true
  yum:
    name: "{{ nginx_package }}"
    state: installed
  tags: install_nginx
  notify: restart nginx service
    

- name: edit nginx.conf
  lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: "^ *server_name  _;"
    line: "server_name {{ ansible_fqdn }};"
  tags: edit_nginx.conf

- name: nginx is running and enabled
  service:
    name: nginx
    state: started
    enabled: yes

- name: put index.html
  copy:
    src: index.html
    dest: /usr/share/nginx/html
    owner: root
    group: root
    mode: 0644

- name: check nginx
  uri:
    url: http://{{ ansible_fqdn }}